name: Submission

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: ./gradlew test
      - name: Install yq
        run: sudo snap install yq
      - id: set_vars
        name: Set vars
        run: |
          ready=$(cat ./submission.yaml | yq e '.Ready' -)
          name=$(cat ./submission.yaml | yq e '.Name' -)
          echo "::set-output name=ready::$ready"
          echo "::set-output name=name::$name"
      - name: Send notification
        if: ${{ steps.set_vars.outputs.ready == 'true' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: https://sap.webhook.office.com/webhookb2/172cfd75-3336-48bc-b622-48ab804f2961@42f7676c-f455-423c-82f6-dc2d99791af7/IncomingWebhook/db13e2cce44e4d2e91ef2afec695a4e1/e7ec9901-1a5f-4281-bd80-3596fe012516
          title: A candidate has submitted his solution
          summary: ${{ steps.set_vars.outputs.name }} 
          text: |
            Repository Owner: ${{ github.repository_owner }}
            Repository: ${{ github.repository }}
